services:
  app:
    image: "docker.io/glideroggan/wallet-app:latest"
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - PUBLIC_PATH=${PUBLIC_PATH:-./}
    container_name: wallet-app
    ports:
      - "80:80"
    restart: unless-stopped

