services:
  app:
    image: "docker.io/glideroggan/wallet-app:latest"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    ports:
      - "80:80"
    restart: unless-stopped

